language: php

php:
  - 5.3
  - 5.4
  - 5.5

install:
    - composer install

script: phpunit --coverage-text

before_script:
  - composer install

notifications:
  email:
    - github@crazedsanity.com
